// Cache strategy: commit-hash keyed, LRU eviction with minimum guarantee.
//
// Each indexed project stores its call graph under `{project}/.cofe-graph/{commit_hash}.cgraph`.
// A sibling `hits.json` records the last-access Unix timestamp for every entry.
//
// Invariant: the newest MAX_CACHE_ENTRIES entries (by last-access time) are always kept.
// On every save, if the entry count exceeds MAX_CACHE_ENTRIES, the oldest entries are
// removed until the count is back within the limit.
//
// Entries are never evicted on read — only on write — so a quiet but frequently-used
// commit will not be evicted just because it was never re-indexed.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::graph::CallGraph;

const CACHE_DIR: &str = ".cofe-graph";
const MAX_CACHE_ENTRIES: usize = 15;

type HitMap = HashMap<String, u64>;

pub struct Cache {
    pub dir: PathBuf,
    pub commit_hash: String,
}

impl Cache {
    pub fn open(base: &Path) -> Option<Self> {
        let commit_hash = git_head(base)?;
        let dir = base.join(CACHE_DIR);
        std::fs::create_dir_all(&dir).ok()?;
        let gitignore = dir.join(".gitignore");
        if !gitignore.exists() {
            let _ = std::fs::write(
                &gitignore,
                "# This file is auto-generated by cofe-graph\n*\n",
            );
        }
        Some(Self { dir, commit_hash })
    }

    pub fn load(&self) -> Option<CallGraph> {
        let bytes = std::fs::read(self.cgraph_path()).ok()?;
        bincode::deserialize(&bytes).ok()
    }

    pub fn save(&self, graph: &CallGraph) {
        if let Ok(bytes) = bincode::serialize(graph) {
            let _ = std::fs::write(self.cgraph_path(), bytes);
        }
        self.record_hit();
        self.evict_if_needed();
    }

    pub fn record_hit(&self) {
        let mut hits = self.read_hits();
        hits.insert(self.commit_hash.clone(), now_secs());
        self.write_hits(&hits);
    }

    fn cgraph_path(&self) -> PathBuf {
        self.dir.join(format!("{}.cgraph", self.commit_hash))
    }

    fn read_hits(&self) -> HitMap {
        std::fs::read_to_string(self.dir.join("hits.json"))
            .ok()
            .and_then(|s| serde_json::from_str(&s).ok())
            .unwrap_or_default()
    }

    fn write_hits(&self, hits: &HitMap) {
        if let Ok(s) = serde_json::to_string(hits) {
            let _ = std::fs::write(self.dir.join("hits.json"), s);
        }
    }

    fn evict_if_needed(&self) {
        let mut hits = self.read_hits();
        if hits.len() <= MAX_CACHE_ENTRIES {
            return;
        }
        let mut entries: Vec<(String, u64)> = hits.iter().map(|(k, v)| (k.clone(), *v)).collect();
        entries.sort_by_key(|(_, t)| *t);
        for (hash, _) in entries.iter().take(entries.len() - MAX_CACHE_ENTRIES) {
            let _ = std::fs::remove_file(self.dir.join(format!("{hash}.cgraph")));
            hits.remove(hash);
        }
        self.write_hits(&hits);
    }
}

fn git_head(repo: &Path) -> Option<String> {
    let out = Command::new("git")
        .args(["-C", repo.to_str()?, "rev-parse", "HEAD"])
        .output()
        .ok()?;
    if out.status.success() {
        Some(String::from_utf8(out.stdout).ok()?.trim().to_string())
    } else {
        None
    }
}

fn now_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}
